# -*- coding: utf-8 -*-
"""meetinggeneration

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VmGAo8FHcvoh90OAY6iFNVOS3TG5ka3s
"""

import pandas as pd
from datetime import datetime
print("MEETING MINUTES GENERATOR\n")
meeting_title=input("enter meeting title:")
date=input("enter meeting date(DD-MM-YYYY):")
time=input("enter meeting time:")
participants=input("enter participants (comma separated):")
agenda=input("enter agenda points(comma separted):")
decisions=input("enter meeting decisions taken(comma separated):")
actions_items=input("enter action items(comma separated):")
prepared_by=input("prepared by:")
participants_list=[p.strip() for p in participants.split(",") if p.strip()]
agenda_list=[a.strip() for a in agenda.split(",") if a.strip()]
decisions_list=[d.strip() for d in decisions.split(",") if d.strip()]
actions_list=[a.strip() for a in actions_items.split(",") if a.strip()]
minutes={
  "meeting title":meeting_title,
  "date":date,
  "time":time,
  "participants":", ".join(participants_list),
  "agenda":"; ".join(agenda_list),
  "decisions taken":"; ".join(decisions_list),
  "action items":"; ".join(actions_list),
  "prepared by":prepared_by,
  "generated on":datetime.now().strftime("%d-%m-%Y %H:%M:%S")
}
df=pd.DataFrame(list(minutes.items()),columns=["field","details"])
print("\n meeting minutes generated successfully\n")
display(df)
df.to_csv("meeting_minutes.csv",index=False)
print("\n file saved as meeting_minutes.csv")