# -*- coding: utf-8 -*-
"""timetablegeneration

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1761wfHZrXfKDNcvpepPxn9Sc42ChaF_s
"""

import pandas as pd
import random
print("TIMETABLE GENERATOR\n")
subjects_input=input("enter subjects(comma seperated):")
days_input=input("enter days(comma separated):")
periods_per_day=int(input("enter no.of periods per day: "))
subjects=[s.strip() for s in subjects_input.split(",") if s.strip()]
days=[d.strip() for d in days_input.split(",") if d.strip()]
if len(subjects)==0 or len(days)==0 or periods_per_day<=0:
  print("invalid input.please try again.")
else:
  timetable={}
  for day in days:
    timetable[day] = random.choices(subjects, k=periods_per_day)
  df=pd.DataFrame(timetable)
  df.index=[f"period{i+1}"for i in range(periods_per_day)]
  print("\ntimetable generated succesfully\n")
  display(df)
  df.to_csv("timetable.csv")
  print("\ntimetable saved as timetable.csv")

